ALTER TABLE [dbo].[Attribute]
    ADD CONSTRAINT [PK_Attribute] PRIMARY KEY CLUSTERED ([Attribute_ID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

