ALTER TABLE [dbo].[ShapeType]
    ADD CONSTRAINT [PK_ShapeType] PRIMARY KEY CLUSTERED ([ShapeType_ID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

