'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
'
Namespace kspiller601
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PLMembershipWSSoap", [Namespace]:="http://tempuri.org/PLMembershipWS/PLMembershipWS")>  _
    Public Class PLMembershipWS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://kspiller601/PLMembershipWS/plmembershipws.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/DPAPIEncryptMachine", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DPAPIEncryptMachine(ByVal data As String) As String
            Dim results() As Object = Me.Invoke("DPAPIEncryptMachine", New Object() {data})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginDPAPIEncryptMachine(ByVal data As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DPAPIEncryptMachine", New Object() {data}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndDPAPIEncryptMachine(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/DPAPIDecryptMachine", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DPAPIDecryptMachine(ByVal data As String) As String
            Dim results() As Object = Me.Invoke("DPAPIDecryptMachine", New Object() {data})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginDPAPIDecryptMachine(ByVal data As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DPAPIDecryptMachine", New Object() {data}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndDPAPIDecryptMachine(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/DPAPIEncryptUser", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DPAPIEncryptUser(ByVal data As String) As String
            Dim results() As Object = Me.Invoke("DPAPIEncryptUser", New Object() {data})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginDPAPIEncryptUser(ByVal data As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DPAPIEncryptUser", New Object() {data}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndDPAPIEncryptUser(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/DPAPIDecryptUser", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DPAPIDecryptUser(ByVal data As String) As String
            Dim results() As Object = Me.Invoke("DPAPIDecryptUser", New Object() {data})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginDPAPIDecryptUser(ByVal data As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DPAPIDecryptUser", New Object() {data}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndDPAPIDecryptUser(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/GetProtectedResource", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProtectedResource(ByVal resourceName As String) As String
            Dim results() As Object = Me.Invoke("GetProtectedResource", New Object() {resourceName})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetProtectedResource(ByVal resourceName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetProtectedResource", New Object() {resourceName}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetProtectedResource(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/GetUserasXmlString", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserasXmlString(ByVal filter As String, ByVal properties As String) As String
            Dim results() As Object = Me.Invoke("GetUserasXmlString", New Object() {filter, properties})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetUserasXmlString(ByVal filter As String, ByVal properties As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetUserasXmlString", New Object() {filter, properties}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetUserasXmlString(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/IsUserInGroup", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsUserInGroup(ByVal groupName As String, ByVal userId As String) As Boolean
            Dim results() As Object = Me.Invoke("IsUserInGroup", New Object() {groupName, userId})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginIsUserInGroup(ByVal groupName As String, ByVal userId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("IsUserInGroup", New Object() {groupName, userId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndIsUserInGroup(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/UserListForGroup", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UserListForGroup(ByVal groupId As String) As String()
            Dim results() As Object = Me.Invoke("UserListForGroup", New Object() {groupId})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginUserListForGroup(ByVal groupId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UserListForGroup", New Object() {groupId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUserListForGroup(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/GroupListForUser", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GroupListForUser(ByVal userId As String) As String()
            Dim results() As Object = Me.Invoke("GroupListForUser", New Object() {userId})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGroupListForUser(ByVal userId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GroupListForUser", New Object() {userId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGroupListForUser(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/DoesUserExist", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DoesUserExist(ByVal userId As String) As Boolean
            Dim results() As Object = Me.Invoke("DoesUserExist", New Object() {userId})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginDoesUserExist(ByVal userId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DoesUserExist", New Object() {userId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndDoesUserExist(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/VerifyPassword", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function VerifyPassword(ByVal userId As String, ByVal userPassword As String) As Boolean
            Dim results() As Object = Me.Invoke("VerifyPassword", New Object() {userId, userPassword})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginVerifyPassword(ByVal userId As String, ByVal userPassword As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("VerifyPassword", New Object() {userId, userPassword}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndVerifyPassword(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/GetAttributeArray", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAttributeArray(ByVal userId As String, ByVal attributeName As String) As String()
            Dim results() As Object = Me.Invoke("GetAttributeArray", New Object() {userId, attributeName})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGetAttributeArray(ByVal userId As String, ByVal attributeName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAttributeArray", New Object() {userId, attributeName}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetAttributeArray(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/GetAttribute", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAttribute(ByVal userId As String, ByVal attributeName As String) As String
            Dim results() As Object = Me.Invoke("GetAttribute", New Object() {userId, attributeName})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetAttribute(ByVal userId As String, ByVal attributeName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAttribute", New Object() {userId, attributeName}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetAttribute(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/GetEncryptedString", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEncryptedString(ByVal clearText As String) As String
            Dim results() As Object = Me.Invoke("GetEncryptedString", New Object() {clearText})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetEncryptedString(ByVal clearText As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetEncryptedString", New Object() {clearText}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetEncryptedString(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/GetDecryptedString", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDecryptedString(ByVal encryptedText As String) As String
            Dim results() As Object = Me.Invoke("GetDecryptedString", New Object() {encryptedText})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetDecryptedString(ByVal encryptedText As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetDecryptedString", New Object() {encryptedText}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetDecryptedString(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/GetPlainEncryptedString", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPlainEncryptedString(ByVal clearText As String) As String
            Dim results() As Object = Me.Invoke("GetPlainEncryptedString", New Object() {clearText})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetPlainEncryptedString(ByVal clearText As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetPlainEncryptedString", New Object() {clearText}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetPlainEncryptedString(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/GetPlainDecryptedString", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPlainDecryptedString(ByVal encryptedText As String) As String
            Dim results() As Object = Me.Invoke("GetPlainDecryptedString", New Object() {encryptedText})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetPlainDecryptedString(ByVal encryptedText As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetPlainDecryptedString", New Object() {encryptedText}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetPlainDecryptedString(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/GetUsersAsXML", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUsersAsXML(ByVal FilterText As String, ByVal PropertyNames As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("GetUsersAsXML", New Object() {FilterText, PropertyNames})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginGetUsersAsXML(ByVal FilterText As String, ByVal PropertyNames As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetUsersAsXML", New Object() {FilterText, PropertyNames}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetUsersAsXML(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/GetUserGUID", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserGUID(ByVal UserId As String) As String
            Dim results() As Object = Me.Invoke("GetUserGUID", New Object() {UserId})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetUserGUID(ByVal UserId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetUserGUID", New Object() {UserId}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetUserGUID(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/GetUserDataForGroup", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserDataForGroup(ByVal GroupID As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("GetUserDataForGroup", New Object() {GroupID})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginGetUserDataForGroup(ByVal GroupID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetUserDataForGroup", New Object() {GroupID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetUserDataForGroup(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PLMembershipWS/PLMembershipWS/GroupList", RequestNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", ResponseNamespace:="http://tempuri.org/PLMembershipWS/PLMembershipWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GroupList() As String()
            Dim results() As Object = Me.Invoke("GroupList", New Object(-1) {})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGroupList(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GroupList", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGroupList(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
    End Class
End Namespace
