ALTER TABLE [dbo].[SDLog]
    ADD CONSTRAINT [PK_SDLog] PRIMARY KEY CLUSTERED ([SDLog_ID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

